### ISSUE TITLE
在国际版12.0.2.0 QECMIXM上刷入后，mi 8 UD指纹失效

### ISSUE THREAD

**Issue by zcy85611** [Coconutat/android_kernel_xiaomi_sdm845_exp#1]
如题，在最新的国际版刷入后，指纹完全失效，且亮度调节出现问题，不知您是否有遇到过

我还没有在大陆版的系统上测试，如果您也用的国际版系统，是否可以帮助看看是什么原因？谢谢！

**Comment by Coconutat** [comment]
> 如题，在最新的国际版刷入后，指纹完全失效，且亮度调节出现问题，不知您是否有遇到过
> 
> 我还没有在大陆版的系统上测试，如果您也用的国际版系统，是否可以帮助看看是什么原因？谢谢！

我使用的是CN的。指纹可能是因为驱动问题。但是我手机更换LCD屏幕了（无指纹屏幕），所以无法测试，很难修复。
