### ISSUE TITLE
Unsupported device

### ISSUE THREAD

**Issue by shidalao** [Coconutat/android_kernel_xiaomi_sdm845_exp#2]
Hi,

`
Mi 8
Miui 12.5.2
Andrdoid 10
Magisk 25.2`

After "Checking device...", it turns out an error with "Unsupported device. Aborting"

**Comment by Coconutat** [comment]
> Hi,
> 
> ` Mi 8 Miui 12.5.2 Andrdoid 10 Magisk 25.2`
> 
> After "Checking device...", it turns out an error with "Unsupported device. Aborting"

Yes,right now dipper(Mi 8) still doesn't support.I had find a way to support it.

**Comment by Coconutat** [comment]
> Hi,
> 
> ` Mi 8 Miui 12.5.2 Andrdoid 10 Magisk 25.2`
> 
> After "Checking device...", it turns out an error with "Unsupported device. Aborting"

Warning:Don't use Magisk with KernelSU.

**Comment by Coconutat** [comment]
> Hi,
> 
> ` Mi 8 Miui 12.5.2 Andrdoid 10 Magisk 25.2`
> 
> After "Checking device...", it turns out an error with "Unsupported device. Aborting"

Please try this:https://github.com/Coconutat/android_kernel_xiaomi_sdm845_exp/releases/tag/KSU_0.6.7%2B

**Comment by shidalao** [comment]
Nice, I will give it a try and let you if it works or not.

**Comment by shidalao** [comment]
it works :)

**Comment by Coconutat** [comment]
> it works :)

OK
