### ISSUE TITLE
How to build this source code

### ISSUE THREAD

**Issue by shidalao** [Coconutat/android_kernel_xiaomi_sdm845_exp#3]
Hi, RT

Ubuntu 18.04 with every step descibed in build_kernel.yml and build_kernel_dipper.sh, but here are two error:

1:
`CC      fs/f2fs/checkpoint.o`
`CC      kernel/time/sched_clock.o`
`CC      lib/zlib_deflate/deflate_syms.o`
`CC      drivers/clk/qcom/clk-pll.o`
`CC      fs/ext4/namei.o`
`DTC     arch/arm64/boot/dts/qcom/dipper-p0-v2-overlay.dtbo`
`Error: ../arch/arm64/boot/dts/qcom/dsi-panel-sim-video.dtsi:14.1-10 syntax error`
`FATAL ERROR: Unable to parse input tree`
`scripts/Makefile.dtbo:24: recipe for target 'arch/arm64/boot/dts/qcom/dipper-p0-v2-overlay.dtbo' failed
`

2:
`CC      drivers/kernelsu/uid_observer.o`
`../drivers/input/touchscreen/focaltech_touch/focaltech_flash.c:48:33: fatal error: include/firmware/fw_ft8719_e10.i: No such file or directory`
`compilation terminated.`
`../scripts/Makefile.build:339: recipe for target 'drivers/input/touchscreen/focaltech_touch/focaltech_flash.o' failed
make[5]: *** [drivers/input/touchscreen/focaltech_touch/focaltech_flash.o] Error 1`

**Comment by Coconutat** [comment]
must be the some file missed.You can clone this :https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/dipper-q-oss
then copy this repo file to dipper-q-oss,

**Comment by shidalao** [comment]
Building the source code from dipper-q-oss branch are just fine, but after flashing into the device, its wlan and sound are not function well. guessing some files are missing too, therefore tried mod its moule.c file to force loading module, and it turns out fine, the very last challenge is KSU module are disabled with balabala overlays info . How do you fix this ?

**Comment by shidalao** [comment]
Under that circumstances, just tried your project and no success :)

**Comment by Coconutat** [comment]
> Building the source code from dipper-q-oss branch are just fine, but after flashing into the device, its wlan and sound are not function well. guessing some files are missing too, therefore tried mod its moule.c file to force loading module, and it turns out fine, the very last challenge is KSU module are disabled with balabala overlays info . How do you fix this ?

Will,Need Xiaomi's open-source Qualcomm driver in another repo.

**Comment by Coconutat** [comment]
I upload missed firmware. 
About dtc issuse.Please install dtc tools.
```
sudo apt-get install device-tree-compiler
```

**Comment by Coconutat** [comment]
> Under that circumstances, just tried your project and no success :)

Now I compiled a Kernel.https://github.com/Coconutat/android_kernel_xiaomi_sdm845_exp/releases/tag/KSU_0.6.8%2B

**Comment by shidalao** [comment]
Nice to hear that, will give it a try :)
